### PR TITLE
Update Chart to latest binary v1.5.2

### PR DESCRIPTION
**Pull request by mannp**
Latest binary is at v1.5.2 and this is a proposed tweak to move to v1.5.2

### CODE REVIEW

**Comment by jahanson** [comment]
@he2ss this chart is still v1.4.5 is there a reason we can't update the chart to v1.5.2?

**Comment by DeathCamel58** [comment]
Would love this PR merged if possible.

**Comment by RelativeSure** [comment]
> Would love this PR merged if possible.

Same here. I work around using the "image.tag" variable in the helmrelease to specify 1.5.2, works fine that way.

**Comment by LaurenceJJones** [comment]
Hey all, can someone confirm that #102 is valid and I should not merge this PR?

**Comment by mannp** [comment]
> image.tag

Strange, this didn't work for me, which is why I created the PR.

**Comment by RelativeSure** [comment]
> > image.tag
> 
> Strange, this didn't work for me, which is why I created the PR.

What error are you getting? I have been using 1.5.2 fine for a few days now.
image

**Review by mmetc — APPROVED** [review]

**Pull request merged**
