### PR TITLE
Prevent secret regeneration with helm update

### LINKED ISSUE #10: agent-credentials are overwritten with each helm apply
If you don't specify agent credentials then the generated ones will be overwritten every time you update the helm chart. If you restart afterwards the agent pod without restarting the lapi pod, the agent is constantly crashing due to invalid credentials.

### PR DESCRIPTION
**Pull request by flo-mic**
This PR fixes #10. Basically it updates the existing secret with either the value from the `secrets.username` and `secrets.password` variable if they are set. If not it checks if the existing secret has some values and will reuse them. Only if the secret is not existing it will generate a new username and password.

### CODE REVIEW

**Review by he2ss — APPROVED** [review]
Hi @flo-mic,

Thanks a lot for this contribution. 
It was one of the last left improvement we wanted to do, so thanks again for this :slightly_smiling_face: .

**Comment by he2ss** [comment]
Hi again @flo-mic,

As the chart release is based on push to master. Could you please pump the chart version from `0.1.4` to `0.1.5` [here](https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/Chart.yaml#L46).

**Comment by flo-mic** [comment]
@he2ss sure will do so later. 

You mentioned this was one of the last improvments that are missing. What else is missing, maybe I can provide a PR. I think for example about and ingress object for the dashboard which can be enabled if needed (default will be disabled)

**Comment by he2ss** [comment]
@flo-mic The two we have in mind were this PR and the PersistentVolume :wink:.
And the dashboard behind Ingress can be a good improvement too :slightly_smiling_face:.

**Comment by flo-mic** [comment]
@he2ss ok the version is increased. Will now continue on the PVC and provide Ingress later

**Pull request merged**
