### PR TITLE
Fix dashboard init trying to ask for confirmation when overwriting existing db

### PR DESCRIPTION
**Pull request by bmalynovytch**
Fix dashboard init trying to ask for confirmation when overwriting existing db (don't overwrite)

Fixes crowdsecurity/helm-charts#86

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
From a quick test it does not seem to work as intended?

```
podman run -v /tmp/:/tmp/ busybox sleep 2 && wget --no-check-certificate "https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip" && unzip metabase_sqlite.zip -nd /tmp/
--2023-12-03 09:57:24--  https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving crowdsec-statics-assets.s3-eu-west-1.amazonaws.com (crowdsec-statics-assets.s3-eu-west-1.amazonaws.com)... 52.92.35.162, 52.218.44.242, 52.218.108.16, ...
Connecting to crowdsec-statics-assets.s3-eu-west-1.amazonaws.com (crowdsec-statics-assets.s3-eu-west-1.amazonaws.com)|52.92.35.162|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

The file is already fully retrieved; nothing to do.

Archive:  metabase_sqlite.zip
caution: filename not matched:  -nd
caution: filename not matched:  /tmp/
```

Checking `/tmp/` has no metabase files even on an empty directory?

**Comment by bmalynovytch** [comment]
> > @LaurenceJJones did you run this in the busybox image provided in the chart ?
> > This fix definitely did the trick in multiple environments.
> 
> Yes, they both use docker.io busybox container. Did you test for when the directory is empty EG on the first deployment?

Sure !

**Comment by he2ss** [comment]
Hi @bmalynovytch,

I think this PR needs to be rebased on main to get the lastest update on your [other PR](#124) we merged recently.

**Review by he2ss — APPROVED** [review]

**Pull request merged**
