### PR TITLE
Support for LAPI High availability

### PR DESCRIPTION
**Pull request by erwanval**
- Add "lapi.replicas" in values and deployment templates
- Add "lapi.affinity" in values.yaml, as it was missing, and thus not included in the the documentation
- Add "lapi.topologySpreadConstraints" in values and deployment template.
- Add a configuration override, to be able to configure and external DB (among other things, as described [here](https://docs.crowdsec.net/docs/configuration/crowdsec_configuration/#configuration-example)). It creates a "config.yaml.local" file in the crowdsec config directory, so default config values are kept.
- Add "lapi.secrets.csLapiSecret" in values, create a secret and define it as env vars for deployment. This is required because it must be identical for every lapi pods. It will be generated automatically if not specified by the user.
- Add "lapi.extraSecrets" to allow users to specify any extra secrets for lapi. They can then be used as env vars (needed to pass the external DB password for example)
- Document HA in Chart.yaml.

### CODE REVIEW

**Comment by michalkutrzeba-odrabiamy** [comment]
Also, there is a bug in loading value in config so it wont work in version v.1.5.2, we need to update to v1.5.2.
`docker_start.sh` loads values directly from `config.yaml` skipping `config.yaml.local` in v1.5.3 it is fixed.

**Comment by he2ss** [comment]
Hi @erwanval,

For information, here is the draft PR (https://github.com/crowdsecurity/crowdsec/pull/2506) that improves the HA handling in crowdsec.
I propose to merge this when the next stable will be available.

**Comment by he2ss** [comment]
Hi @erwanval,

the PR on crowdsec is merged.
Let's now wait for the release to bump here the docker image and merge this PR.


And sorry again for the delay.

**Comment by he2ss** [comment]
Hi @erwanval,

We released [new rc](https://github.com/crowdsecurity/crowdsec/releases/tag/v1.6.1-rc1) and here is the [docker image](https://hub.docker.com/layers/crowdsecurity/crowdsec/v1.6.1-rc1/images/sha256-0d6b3de743eec4cd79fd571f9f76271123e1a3bbdcdacb8c82e39446c427d391?context=explore).

Do you think you can try using this image and see if it's working as you expected with this PR ?

**Comment by erwanval** [comment]
Hi @he2ss,

Sorry for the delay, I tested using the v1.6.1-rc1 image, and everything works as expected on my side.
I have seen v1.6.1-rc2 has been released since, but there is no docker image for it, so I haven't tested that one.

Also, I resolved the conflict

**Comment by erwanval** [comment]
Yes, thank you !

**Review by he2ss — APPROVED** [review]

**Pull request merged**
