### PR TITLE
Convert Appsec deployment into daemonset for high availability

### PR DESCRIPTION
**Pull request by srkoster**
Thanks @he2ss for implementing Appsec into the Crowdsec helmchart. This PR builds upon #189 and turns the Appsec deployment into a daemonset for high availibility.

Other changes:
- RegistrationToken generation is moved into `_helpers.tpl`. It can now also be passed through `values.yaml`
- `appsec-daemonSet.yaml` is structured more like `agent-daemonSet.yaml`
- Added the appsec auto_registration config into `values.yaml`

### CODE REVIEW

**Comment by he2ss** [comment]
Hi @srkoster,

Thanks for this contribution. Isn't it better to let it on deployment, as it suits better if you want to configure HA?
If you have many nodes and don't want to deploy an appsec per node, you will have to play with annotations. Instead, having a deployment with replicas can be better, IMO.

**Comment by srkoster** [comment]
@he2ss sounds reasonable. 

I decided to implement the daemonset as the agent was also deployed as a daemonset. I see that the newest chart version allows the user to make a choice between deployment and daemonset. Does it make sense to bake the same choice into appsec?

**Comment by srkoster** [comment]
Closing this PR in favor of #208

**Pull request closed without merging**
